--E・HERO シャイニング・フェニックスガイ
function c88820237.initial_effect(c)
	--fusion material
	c:EnableReviveLimit()
	Duel.EnableGlobalFlag(GLOBALFLAG_SPSUMMON_COUNT)
	--aux.AddFusionProcMixN(c,true,true,aux.FilterBoolFunction(Card.IsSetCard,0x8),3)
	aux.AddFusionProcFunRep(c,aux.FilterBoolFunction(Card.IsFusionSetCard,0x8),3,true)
	--aux.AddFusionProcFun2(c,c23204029.ffilter2,c23204029.ffilter1,true)
	--spsummon condition
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetProperty(EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e1:SetCode(EFFECT_SPSUMMON_CONDITION)
	e1:SetValue(aux.fuslimit)
	c:RegisterEffect(e1)
	--indes
	local e2=Effect.CreateEffect(c)
	e2:SetType(EFFECT_TYPE_SINGLE)
	e2:SetCountLimit(1)
	e2:SetCode(EFFECT_INDESTRUCTABLE)
	e2:SetValue(1)
	c:RegisterEffect(e2)
	--atkup
	local e3=Effect.CreateEffect(c)
	e3:SetType(EFFECT_TYPE_SINGLE)
	e3:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e3:SetRange(LOCATION_MZONE)
	e3:SetCode(EFFECT_UPDATE_ATTACK)
	e3:SetValue(c88820237.atkup)
	c:RegisterEffect(e3)
	--Pos Change
	local e3=Effect.CreateEffect(c)
	e3:SetType(EFFECT_TYPE_FIELD)
	e3:SetCode(EFFECT_SET_POSITION)
	e3:SetProperty(EFFECT_FLAG_SET_AVAILABLE)
	e3:SetRange(LOCATION_MZONE)
	e3:SetTargetRange(0,LOCATION_MZONE)
	e3:SetCondition(c88820237.poscon)
	e3:SetValue(POS_FACEUP_ATTACK)
	c:RegisterEffect(e3)

	--must attack
	--local e4=Effect.CreateEffect(c)
	--e4:SetType(EFFECT_TYPE_FIELD)
	--e4:SetCode(EFFECT_MUST_ATTACK)
	--e4:SetRange(LOCATION_MZONE)
	--e4:SetTargetRange(0,LOCATION_MZONE)
	--e4:SetCondition(c88820237.poscon)
	--c:RegisterEffect(e4)
	--local e5=e4:Clone()
	--e5:SetCode(EFFECT_MUST_ATTACK_MONSTER)
	--c:RegisterEffect(e5)
	--local e6=Effect.CreateEffect(c)
	--e6:SetType(EFFECT_TYPE_SINGLE)
	--e6:SetCode(EFFECT_MUST_BE_ATTACKED)
	--e6:SetValue(1)
	--c:RegisterEffect(e6)
	--must attack
	local e4=Effect.CreateEffect(c)
	e4:SetType(EFFECT_TYPE_FIELD)
	e4:SetCode(EFFECT_MUST_ATTACK)
	e4:SetRange(LOCATION_MZONE)
	e4:SetTargetRange(0,LOCATION_MZONE)
	c:RegisterEffect(e4)
	local e5=Effect.CreateEffect(c)
	e5:SetType(EFFECT_TYPE_SINGLE)
	e5:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e5:SetCode(EFFECT_MUST_BE_ATTACKED)
	e5:SetRange(LOCATION_MZONE)
	e5:SetValue(aux.imval1)
	c:RegisterEffect(e5)
	local e07=Effect.CreateEffect(c)
	e07:SetType(EFFECT_TYPE_SINGLE)
	e07:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e07:SetRange(LOCATION_MZONE)
	e07:SetCode(EFFECT_ADD_ATTRIBUTE)
	e07:SetValue(0x10)
	c:RegisterEffect(e07)
	--spsummon count limit
	local e04=Effect.CreateEffect(c)
	e04:SetType(EFFECT_TYPE_FIELD)
	e04:SetCode(EFFECT_SPSUMMON_COUNT_LIMIT)
	e04:SetRange(LOCATION_MZONE)
	e04:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e04:SetTargetRange(1,0)
	e04:SetValue(1)
	c:RegisterEffect(e04)
end
c88820237.material_setcode={0x8,0x3008}
function c88820237.atkup(e,c)
	return Duel.GetMatchingGroupCount(Card.IsSetCard,c:GetControler(),LOCATION_GRAVE,0,nil,0x8)*300
end
function c88820237.poscon(e)
	local ph=Duel.GetCurrentPhase()
	return Duel.GetTurnPlayer()~=e:GetHandlerPlayer() and ph>=0x8 and ph<=0x20
end
